---
# tasks file for apt_sources
#

- name: configure main apt sources.list
  action:
    module:     template
    src:        sources.list.j2
    dest:       '{{ apt_sources_path }}'
    backup:     yes
  notify:
  - apt-update-cache

